package pe.gob.reniec.certificados.cancelacion.cancellation.identity;

public enum IdentityFailure {
	UNAUTHORIZED,
	IN_PROGRESS,
	INVALID_STATE,
	STATE_EXPIRED,
	CALLBACK_REPLAYED,
	INVALID_CALLBACK,
	CANCELLED,
	REJECTED,
	IDENTITY_MISMATCH,
	TOKEN_REJECTED,
	TOKEN_INVALID,
	TIMEOUT,
	UNAVAILABLE,
	INVALID_RESPONSE,
	CONFIGURATION
}
