package pe.gob.reniec.credenciales.revocacion.revocation.persistence;

public enum RevocationAuditEventType {
	REQUEST_STARTED,
	ELIGIBILITY_CHECKED,
	DIGITAL_CREDENTIALS_AVAILABLE,
	REQUEST_NOT_ELIGIBLE,
	IDENTITY_VERIFICATION_STARTED,
	IDENTITY_VERIFIED,
	DIGITAL_CREDENTIAL_LIST_REQUESTED,
	DIGITAL_CREDENTIAL_LIST_REFRESHED,
	DIGITAL_CREDENTIAL_LIST_REVALIDATED,
	DIGITAL_CREDENTIAL_SELECTION_STALE,
	DIGITAL_CREDENTIALS_SELECTED,
	DIGITAL_CREDENTIAL_LIST_EMPTY,
	DIGITAL_CREDENTIAL_LIST_FAILED,
	REQUEST_RECOVERED,
	REASON_REGISTERED,
	CONSENT_CONFIRMED,
	REVOCATION_PREPARED,
	REVOCATION_SUBMITTED,
	REVOCATION_CONFIRMED,
	OUTCOME_UNKNOWN,
	RECEIPT_GENERATED,
	RECEIPT_GENERATION_FAILED,
	REQUEST_ABANDONED
}
