package pe.gob.reniec.credenciales.revocacion.revocation.persistence;

import io.swagger.v3.oas.annotations.media.Schema;

@Schema(description = "Estado actual de la solicitud ciudadana de revocación.")
public enum RevocationRequestStatus {
	STARTED,
	CHECKING_AVAILABILITY,
	NO_DIGITAL_CREDENTIALS_AVAILABLE,
	PENDING_IDENTITY_VERIFICATION,
	IDENTITY_VERIFIED,
	AUTHENTICATED_PENDING_DIGITAL_CREDENTIAL_LIST,
	CHECKING_DIGITAL_CREDENTIAL_LIST,
	DIGITAL_CREDENTIALS_AVAILABLE,
	DIGITAL_CREDENTIALS_SELECTED,
	REASON_REGISTERED,
	PENDING_CONFIRMATION,
	CONFIRMED,
	REVOCATION_IN_PROGRESS,
	REVOCATION_SUCCEEDED,
	REVOCATION_FAILED,
	REVOCATION_OUTCOME_UNKNOWN,
	COMPLETED,
	FAILED,
	OUTCOME_UNKNOWN,
	RECEIPT_AVAILABLE,
	ABANDONED
}
