package pe.gob.reniec.certificados.cancelacion.cancellation.persistence;

public enum CancellationAuditEventType {
	REQUEST_STARTED,
	ELIGIBILITY_CHECKED,
	CERTIFICATES_AVAILABLE,
	REQUEST_NOT_ELIGIBLE,
	IDENTITY_VERIFICATION_STARTED,
	IDENTITY_VERIFIED,
	CERTIFICATES_SELECTED,
	REQUEST_RECOVERED,
	REASON_REGISTERED,
	CONSENT_CONFIRMED,
	REVOCATION_PREPARED,
	REVOCATION_SUBMITTED,
	REVOCATION_CONFIRMED,
	OUTCOME_UNKNOWN,
	RECEIPT_GENERATED,
	REQUEST_ABANDONED
}
