spring:
  application:
    name: ${APP_NAME:cancelacion-certificados-backend}
  flyway:
    clean-disabled: true
    enabled: true
    validate-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
  show-actuator: true
  paths-to-match:
    - /api/v1/**
    - /actuator/health

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:}

server:
  port: ${SERVER_PORT:8080}
  error:
    include-message: never
    include-binding-errors: never
    include-stacktrace: never
    include-exception: false

management:
  health:
    db:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

logging:
  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} %-5level [%X{correlationId:-no-correlation}] %logger{36} - %msg%n"
  level:
    root: ${LOG_LEVEL_ROOT:INFO}
    pe.gob.reniec.certificados.cancelacion: ${LOG_LEVEL_APP:INFO}
