spring:
  config:
    activate:
      on-profile: local
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3307}/${DB_NAME:cancelacion_certificados}?connectionTimeZone=UTC&forceConnectionTimeZoneToSession=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

logging:
  level:
    pe.gob.reniec.certificados.cancelacion: ${LOG_LEVEL_APP:DEBUG}
