spring:
  config:
    activate:
      on-profile: test
  datasource:
    hikari:
      connection-timeout: 1000
      validation-timeout: 1000

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: false

app:
  frontend-base-url: http://localhost:3000
  backend-base-url: http://localhost:8080
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}
  availability:
    stale-attempt-threshold: 100ms
    timeout: 100ms
    mock:
      simulated-timeout: 300ms
  recaptcha:
    mode: mock
  id-peru:
    mode: mock
    flow-secret: MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY=
    mock-scenario: MATCH

server:
  port: 0

management:
  endpoint:
    health:
      cache:
        time-to-live: 0

logging:
  level:
    root: ${LOG_LEVEL_ROOT:WARN}
    pe.gob.reniec.certificados.cancelacion: ${LOG_LEVEL_APP:WARN}
