spring:
  config:
    activate:
      on-profile: prod

app:
  credential-provider:
    mode: real
    base-url: ${CREDENTIAL_PROVIDER_BASE_URL}
    api-key: ${CREDENTIAL_PROVIDER_API_KEY}
    connect-timeout: ${CREDENTIAL_PROVIDER_CONNECT_TIMEOUT:3s}
    read-timeout: ${CREDENTIAL_PROVIDER_READ_TIMEOUT:5s}
  session:
    signing-secret: ${SESSION_SIGNING_SECRET}
    cookie-secure: true
  frontend-base-url: ${APP_FRONTEND_BASE_URL}
  backend-base-url: ${APP_BACKEND_BASE_URL}
  id-peru:
    mode: real
    version: v2
    client-id: ${ID_PERU_CLIENT_ID}
    client-secret: ${ID_PERU_CLIENT_SECRET}
    referer: ${ID_PERU_REFERER}
    flow-secret: ${ID_PERU_FLOW_SECRET}
